var capDesc = {
  SETPCAP: '修改流程能力。',
  MKNOD: '使用 mknod(2) 创建特殊文件。',
  AUDIT_WRITE: '向内核审计日志写入记录。',
  CHOWN: '对文件UID和GID进行任意修改（见chown(2)）。',
  NET_RAW: '使用RAW和PACKET套接字。',
  DAC_OVERRIDE: '绕过文件读、写和执行权限检查。',
  FOWNER: '绕过通常要求进程的文件系统UID与文件的UID匹配的操作的权限检查。',
  FSETID: '当一个文件被修改时，不要清除set-user-ID和set-group-ID权限位。',
  KILL: '绕过发送信号的权限检查。',
  SETGID: '对进程GID和补充GID列表进行任意操作。',
  SETUID: '对进程UID进行任意的操作。',
  NET_BIND_SERVICE: '将一个套接字绑定到互联网领域的特权端口（端口号小于1024）。',
  SYS_CHROOT: '使用chroot(2)，改变根目录。',
  SETFCAP: '设置文件能力。',
  SYS_MODULE: '加载和卸载内核模块。',
  SYS_RAWIO: '执行I/O端口操作（iopl(2)和ioperm(2)）。',
  SYS_PACCT: '使用acct(2)，打开或关闭进程会计。',
  SYS_ADMIN: '执行一系列的系统管理操作。',
  SYS_NICE: '提高进程的 nice 值（nice(2), setpriority(2)），改变任意进程的 nice 值。',
  SYS_RESOURCE: '覆盖资源限制。',
  SYS_TIME: '设置系统时钟（settimeofday(2), stime(2), adjtimex(2)）；设置实时（硬件）时钟。',
  SYS_TTY_CONFIG: '使用 vhangup(2) ；在虚拟终端上采用各种特权 ioctl(2) 操作。',
  AUDIT_CONTROL: '启用和禁用内核审计；改变审计过滤规则；检索审计状态和过滤规则。',
  MAC_ADMIN: '允许MAC配置或状态改变。已为Smack LSM实施。',
  MAC_OVERRIDE: '覆盖强制访问控制（MAC）。为Smack Linux安全模块（LSM）实施。',
  NET_ADMIN: '执行各种与网络有关的操作。',
  SYSLOG: '执行特权的 syslog(2) 操作。',
  DAC_READ_SEARCH: '绕过文件读取权限检查和目录读取和执行权限检查。',
  LINUX_IMMUTABLE: '设置 FS_APPEND_FL 和 FS_IMMUTABLE_FL i-node 标记。',
  NET_BROADCAST: '进行套接字广播，并收听组播。',
  IPC_LOCK: '锁定内存（mlock(2), mlockall(2), mmap(2), shmctl(2)）。',
  IPC_OWNER: '绕过对System V IPC对象操作的权限检查。',
  SYS_PTRACE: '使用 ptrace(2) 跟踪任意进程。',
  SYS_BOOT: '使用reboot(2)和kexec_load(2)，重新启动并加载一个新的内核以便以后执行。',
  LEASE: '在任意文件上建立租约（见 fcntl(2)）。',
  WAKE_ALARM: '触发一些能唤醒系统的东西。',
  BLOCK_SUSPEND: '采用可以阻止系统暂停的功能。',
};

export function ContainerCapabilities() {
  // all capabilities can be found at https://docs.docker.com/engine/reference/run/#runtime-privilege-and-linux-capabilities
  return [
    new ContainerCapability('SETPCAP', true),
    new ContainerCapability('MKNOD', true),
    new ContainerCapability('AUDIT_WRITE', true),
    new ContainerCapability('CHOWN', true),
    new ContainerCapability('NET_RAW', true),
    new ContainerCapability('DAC_OVERRIDE', true),
    new ContainerCapability('FOWNER', true),
    new ContainerCapability('FSETID', true),
    new ContainerCapability('KILL', true),
    new ContainerCapability('SETGID', true),
    new ContainerCapability('SETUID', true),
    new ContainerCapability('NET_BIND_SERVICE', true),
    new ContainerCapability('SYS_CHROOT', true),
    new ContainerCapability('SETFCAP', true),
    new ContainerCapability('SYS_MODULE', false),
    new ContainerCapability('SYS_RAWIO', false),
    new ContainerCapability('SYS_PACCT', false),
    new ContainerCapability('SYS_ADMIN', false),
    new ContainerCapability('SYS_NICE', false),
    new ContainerCapability('SYS_RESOURCE', false),
    new ContainerCapability('SYS_TIME', false),
    new ContainerCapability('SYS_TTY_CONFIG', false),
    new ContainerCapability('AUDIT_CONTROL', false),
    new ContainerCapability('MAC_ADMIN', false),
    new ContainerCapability('MAC_OVERRIDE', false),
    new ContainerCapability('NET_ADMIN', false),
    new ContainerCapability('SYSLOG', false),
    new ContainerCapability('DAC_READ_SEARCH', false),
    new ContainerCapability('LINUX_IMMUTABLE', false),
    new ContainerCapability('NET_BROADCAST', false),
    new ContainerCapability('IPC_LOCK', false),
    new ContainerCapability('IPC_OWNER', false),
    new ContainerCapability('SYS_PTRACE', false),
    new ContainerCapability('SYS_BOOT', false),
    new ContainerCapability('LEASE', false),
    new ContainerCapability('WAKE_ALARM', false),
    new ContainerCapability('BLOCK_SUSPEND', false),
  ].sort(function (a, b) {
    return a.capability < b.capability ? -1 : 1;
  });
}

export function ContainerCapability(cap, allowed) {
  this.capability = cap;
  this.allowed = allowed;
  this.description = capDesc[cap];
}
